-- MySQL Script generated by MySQL Workbench
-- Tue May 23 12:23:33 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema NFL-DataBase
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema NFL-DataBase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `NFL-DataBase` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `NFL-DataBase` ;

-- -----------------------------------------------------
-- Table `NFL-DataBase`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NFL-DataBase`.`city` (
  `id_city` INT NOT NULL AUTO_INCREMENT,
  `name_city` VARCHAR(45) NOT NULL,
  `county` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_city`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `NFL-DataBase`.`coach`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NFL-DataBase`.`coach` (
  `id_coach` INT NOT NULL AUTO_INCREMENT,
  `name_coach` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_coach`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `NFL-DataBase`.`injury`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NFL-DataBase`.`injury` (
  `id_injury` INT NOT NULL AUTO_INCREMENT,
  `type_injury` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_injury`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `NFL-DataBase`.`position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NFL-DataBase`.`position` (
  `id_position` INT NOT NULL AUTO_INCREMENT,
  `name_position` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_position`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `NFL-DataBase`.`team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NFL-DataBase`.`team` (
  `id_team` INT NOT NULL AUTO_INCREMENT,
  `team_name` VARCHAR(45) NOT NULL,
  `captain` INT NULL DEFAULT NULL,
  `id_city` INT NULL DEFAULT NULL,
  `id_coach` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_team`),
  INDEX `id_city_idx` (`id_city` ASC) VISIBLE,
  INDEX `id_coach_idx` (`id_coach` ASC) VISIBLE,
  CONSTRAINT `id_city`
    FOREIGN KEY (`id_city`)
    REFERENCES `NFL-DataBase`.`city` (`id_city`),
  CONSTRAINT `id_coach`
    FOREIGN KEY (`id_coach`)
    REFERENCES `NFL-DataBase`.`coach` (`id_coach`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `NFL-DataBase`.`players`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NFL-DataBase`.`players` (
  `id_players` INT NOT NULL AUTO_INCREMENT,
  `name_player` VARCHAR(45) NULL DEFAULT NULL,
  `last_name` VARCHAR(45) NULL DEFAULT NULL,
  `skill_level` VARCHAR(45) NULL DEFAULT NULL,
  `id_team` INT NULL DEFAULT NULL,
  `id_position` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_players`),
  INDEX `id_team_idx` (`id_team` ASC) VISIBLE,
  INDEX `id_position_idx` (`id_position` ASC) VISIBLE,
  CONSTRAINT `id_position`
    FOREIGN KEY (`id_position`)
    REFERENCES `NFL-DataBase`.`position` (`id_position`),
  CONSTRAINT `id_team`
    FOREIGN KEY (`id_team`)
    REFERENCES `NFL-DataBase`.`team` (`id_team`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `NFL-DataBase`.`injury_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NFL-DataBase`.`injury_record` (
  `id_injury_record` INT NOT NULL AUTO_INCREMENT,
  `id_injury` INT NULL DEFAULT NULL,
  `id_player` INT NULL DEFAULT NULL,
  `date_injury` DATETIME NULL DEFAULT NULL,
  `status` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_injury_record`),
  INDEX `id_injury_idx` (`id_injury` ASC) VISIBLE,
  INDEX `id_player_idx` (`id_player` ASC) VISIBLE,
  CONSTRAINT `id_injury`
    FOREIGN KEY (`id_injury`)
    REFERENCES `NFL-DataBase`.`injury` (`id_injury`),
  CONSTRAINT `id_player`
    FOREIGN KEY (`id_player`)
    REFERENCES `NFL-DataBase`.`players` (`id_players`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `NFL-DataBase`.`match`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NFL-DataBase`.`match` (
  `id_match` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NULL DEFAULT NULL,
  `home_team` INT NULL DEFAULT NULL,
  `away_team` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_match`),
  INDEX `id_team_idx1` (`home_team` ASC, `away_team` ASC) VISIBLE,
  INDEX `away_team_idx` (`away_team` ASC) VISIBLE,
  CONSTRAINT `away_team`
    FOREIGN KEY (`away_team`)
    REFERENCES `NFL-DataBase`.`team` (`id_team`),
  CONSTRAINT `home_team`
    FOREIGN KEY (`away_team`)
    REFERENCES `NFL-DataBase`.`team` (`id_team`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `NFL-DataBase`.`score`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NFL-DataBase`.`score` (
  `id_score` INT NOT NULL AUTO_INCREMENT,
  `id_match` INT NULL DEFAULT NULL,
  `home_team_score` INT NULL DEFAULT NULL,
  `away_team_score` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_score`),
  INDEX `id_match_idx` (`id_match` ASC) VISIBLE,
  INDEX `home_team_score_idx` (`home_team_score` ASC) VISIBLE,
  INDEX `away_team_score_idx` (`away_team_score` ASC) VISIBLE,
  CONSTRAINT `away_team_score`
    FOREIGN KEY (`away_team_score`)
    REFERENCES `NFL-DataBase`.`team` (`id_team`),
  CONSTRAINT `home_team_score`
    FOREIGN KEY (`home_team_score`)
    REFERENCES `NFL-DataBase`.`team` (`id_team`),
  CONSTRAINT `id_match`
    FOREIGN KEY (`id_match`)
    REFERENCES `NFL-DataBase`.`match` (`id_match`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
